title: computer games! # name of the site
author: Ethan Hawkins # name of site's author
email: ethanwhawkins@gmail.com # email of site's author
url: https://www.computer-games.xyz # root address of the site
baseurl: "" # subpath of the site
description: > # description of the site (multiple lines allowed)
  A simple site for my projects, and blogging about lesser known games!

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
